theme: minima
title: Paul Racco's blog
author: Paul Racco
email: pjracco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first attempt at making a blog page.
  How does it look?

# social links
LinkedIn: paul-racco
github_username:  pracco

# is this hidden?

show_excerpts: true # set to false to remove excerpts on the homepage
