#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Paul Racco

# Short bio or description (displayed in the header)
description: An aggressive pedetrian

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: pjracco@gmail.com
  github: pracco
  linkedin: paul-racco

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://pracco.github.io

#
# !! You don't need to change any of the configuration flags below !!
#
